language: java
install: echo "skip 'gradle assemble' step"
script: ./gradlew check
env:
  - GRADLE_OPTS="-Dorg.gradle.daemon=false"
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - $HOME/.m2
before_cache:
  - rm -f $HOME/.gradle/caches/**/*.lock
